version: '3.8'

services:
  # 1. The Cache
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  # 2. The Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: skhan
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: skhan
    ports:
      - "5432:5432"

  # 3. The Go Application (We will build this next)
  # api:
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - postgres
  #     - redis